### ISSUE TITLE
Don't use strip_tags

### ISSUE THREAD

**Issue by xPaw** [ValveSoftware/ArtifactDeckCode#1]
It will unnecessary remove stuff that players might want to use. Just correctly escape the string when displaying it on the site (currently it's entirely relying on strip_tags).

**Comment by JeffAtValve** [comment]
We have an internal version of a function that behaves differently, but for the open source example we used strip_tags as it's a PHP function.  Will add a comment to indicate that people should use their own HTML escaping.  Good catch.
