### ISSUE TITLE
Some cards don't have card_text when they have passive abilities.

### ISSUE THREAD

**Issue by Gorefistus** [ValveSoftware/ArtifactDeckCode#13]
For some reason different cards work differently for example:

- Luna has it's passive in card_text field (as well as references field)
- Meepo only has active ability in his card text (references are fine)
- Crystal Maiden doesn't have any card_text, but she has one passive (references are fine though)

As far as I saw it appears only for passive abilities

**Comment by JeffAtValve** [comment]
This appears fixed in the next api release

**Comment by 731288559** [comment]
Zeus, 10065.
