### ISSUE TITLE
Links to cards artwork in API?

### ISSUE THREAD

**Issue by camperofcamper** [ValveSoftware/ArtifactDeckCode#14]
Is there any plans on adding pure artwork for cards? It might be helpful in some cases like mine. I don't really want to use `large_image` since it will have raster text on image and it looks not really good on retina or when you zoom in on mobile device.Also you can't ctrl+f text

For now as a temporary solution I overlap `large_image` with two div's with `card_name` and `card_text`

I've attached a few files ([source](https://github.com/ottah/ArtifactDB)) to make you understand the idea

![abaddon](https://user-images.githubusercontent.com/2990093/48380912-b3518500-e6ea-11e8-9653-6b9a16d1e67e.jpg)
![altarofthemadmoon](https://user-images.githubusercontent.com/2990093/48380918-b6e50c00-e6ea-11e8-9d83-944117d356a5.jpg)

**Comment by JeffAtValve** [comment]
We will not be providing this at this time.
