### ISSUE TITLE
Horde / Oglodi Catapult naming mismatch

### ISSUE THREAD

**Issue by Shrugtal** [ValveSoftware/ArtifactDeckCode#18]
The CardSet API returns a english card_name for id 10310 of "Horde Catapult", but the image provided in large_image has the name Oglodi Catapult.

It should be one or the other.

**Comment by JeffAtValve** [comment]
This will be addressed at a future date along with other localization changes

**Comment by JeffAtValve** [comment]
This should now be fixed along with a few other mismatches
