### ISSUE TITLE
Deck URLs are broken

### ISSUE THREAD

**Issue by asimonov-im** [ValveSoftware/ArtifactDeckCode#21]
Both of the following URLs now return empty data
https://playartifact.com/cardset/00
https://playartifact.com/cardset/01

Similarly, the deck URLs, such as below, just redirect to https://playartifact.com
https://playartifact.com/d/ADCJQUQI30zuwEYg2ABeF1Bu94BmWIBTEkLtAKlAZakAYmHh0JsdWUvUmVkIEV4YW1wbGU_
https://playartifact.com/d/ADCJWkTZX05uwGDCRV4XQGy3QGLmqUBg4GQJgGLGgO7AaABR3JlZW4vQmxhY2sgRXhhbXBsZQ__

**Comment by asimonov-im** [comment]
And it's fixed. Yay!

**Comment by Shrugtal** [comment]
It did this yesterday for about an hour, I wouldn't open more issues for API downtime.

**Comment by JeffAtValve** [comment]
This can occur when we're pushing updates or doing testing work which is significantly more frequent now than it will be when the game is public.

**Comment by asimonov-im** [comment]
I'll keep that in mind. Thanks for following up!

(I was actually pretty confident that the problem would fix itself, but wanted to file an issue just in case. Plus, the issue should prevent others from being surprised by the occasional downtimes in the future.)

**Comment by JeffAtValve** [comment]
Understandable.  The CDN URL should have close to 100% uptime, but the request API may go down during our maintenance.  If you cache the URL as recommended, you should be good to go.

**Comment by asimonov-im** [comment]
@JeffAtValve Just to clarify, we should be caching the card set data not just the URL. Is that right?

For example https://playartifact.com/cardset/0, returns:
```
{
  "cdn_root": "https:\/\/steamcdn-a.akamaihd.net\/",
  "url": "\/apps\/583950\/resource\/card_set_0.C0748A17E2C08252A9CCE75BB593E62D71DCDA77.json",
  "expire_time": 1542496079
}
```
I took the instructions to mean that we should fetch https://steamcdn-a.akamaihd.net/apps/583950/resource/card_set_0.C0748A17E2C08252A9CCE75BB593E62D71DCDA77.json and cache its contents until the expiration time (as opposed to caching that URL for set 0 and re-fetching the data every time).

**Comment by MisterJimson** [comment]
I also would like this clarified. I assumed we needed to cache the card set json as well.

**Comment by JeffAtValve** [comment]
Yes you should cache the full json blob.
