### ISSUE TITLE
Provide "Get Initiative" as an attribute

### ISSUE THREAD

**Issue by Shrugtal** [ValveSoftware/ArtifactDeckCode#24]
Cards should return a name/value pair that indicates if they have the "Get Initiative" text.

**Comment by tmallonee** [comment]
`is_quick` is available in the Card Set API.

**Comment by Shrugtal** [comment]
I am aware. This issue was created at the request of the developer for tracking, but was never closed. See 
https://github.com/ValveSoftware/ArtifactDeckCode/issues/4#issuecomment-439410555
