### ISSUE TITLE
There is still not other language support.

### ISSUE THREAD

**Issue by cabraG** [ValveSoftware/ArtifactDeckCode#25]
Sorry for that，it's just like the "we need chinese" question on steam.
But it is only 2 day left for the test,and 12 day for release.
Can't  we get the exact time that when this api have other language support ？

**Comment by Shrugtal** [comment]
You're not going to get an exact timeframe from them. This was just answered in the #4 closing message.

**Comment by JeffAtValve** [comment]
You should be able to code your API to work with the existing data.   In the text and image fields, the supported Chinese languages will be schinese and tchinese.  When the API is updated, we will make an update to the README and these fields will start being sent as part of the API.

**Comment by JeffAtValve** [comment]
The first set of languages, including Traditional and Simplified Chinese, were released yesterday.
