### ISSUE TITLE
large_image.default restructure to include english?

### ISSUE THREAD

**Issue by 0ttah** [ValveSoftware/ArtifactDeckCode#27]
I assume at some point in the future there will be alternative art versions of cards and that is why there is the `default` property on card image assets instead of `english`.

Would it make more sense to change `default` to an object with all the languages inside of it and add `english`. This would then make it easier to add new alternative art. 

Example below.

```javascript
{
  "large_image": {
    "default": {
      "english": "https://...png",
      "german": "https://...png",
      "french": "https://...png",
      ...
    },
    "foil":{
      "english": "https://...png",
      "german": "https://...png",
      "french": "https://...png",
      ...
    }
  }
}
```

**Comment by djetelina** [comment]
I agree that english sometimes being under `english` key and sometimes under `default` is less than ideal, personally it makes me do things like [this](https://github.com/iScrE4m/pyArtifact/blob/master/src/pyartifact/sets_and_cards.py#L41)

**Comment by JeffAtValve** [comment]
default is the fallback if the language doesn't exist.  This will always be english.  The API is a bit inconsistent as the text names should using this default pattern but are not.  I can see about adding them as that will be consistent and not break existing users.  For instance, say we add Thai translations in text, but not images.   You would be expected to check for thai in the lists, then fallback to default if not available (or not depending on what your trying to do with the information).

I'll add a note for the default text.

If new cards are ever made that are based on old cards, they will be new card id's with base_card_id set.

**Comment by 0ttah** [comment]
Ah ok that makes sense, thanks for clearing that up @JeffAtValve. I was wondering what the base_card_id was for. 

English becoming default would be great.
