### ISSUE TITLE
Card Price

### ISSUE THREAD

**Issue by edmilsonrobson** [ValveSoftware/ArtifactDeckCode#28]
With the game launching soon, would a card "price" property be something possible, with the cheapest offer of the card in the marketplace? 🤔

**Comment by 0ttah** [comment]
This still works for other games, not sure if Artifact's market place will be different.

`http://steamcommunity.com/market/priceoverview/?appid=730&currency=3&market_hash_name=StatTrak%E2%84%A2 M4A1-S | Hyper Beast (Minimal Wear)`

`{"success":true,"lowest_price":"42,18\u20ac","volume":"5","median_price":"39,43\u20ac"}`

**Comment by JeffAtValve** [comment]
There will be a market api available when the market is available to use.  The README will be updated at that time.
