### ISSUE TITLE
Images of cards are not updated in the API

### ISSUE THREAD

**Issue by camperofcamper** [ValveSoftware/ArtifactDeckCode#32]
Last beta patch bringed on some localization updates. Can't speak for all languages but in russian `"card_text"` for some cards was updated and `"large_image"` wasn't. Some examples
— Battlefield Control
— Eclipse
— Roseleaf Rejuvenator
And around 5 more

**Comment by JeffAtValve** [comment]
Correct.  These will come close to launch.
