### ISSUE TITLE
decoder including the incorrect amount of cards ?

### ISSUE THREAD

**Issue by exts** [ValveSoftware/ArtifactDeckCode#34]
I was testing official deck decoder code, which made me think my golang port was incorrect, but low and behold https://3v4l.org/92LIO

It's showing only 19 cards here for the starter deck https://playartifact.com/d/ADCJRwSJX2Dc7wBEAN4XUFBcN0BQmQBQWABRCgBCgN0AWUBbQFDbwEISEJsdWUvQmxhY2sgQ29udHJvbA__ but there's only 18 normal cards (non duplicate) and 6 items which seem to be missing.

I was checking and it seems like the first 3 cards are items, something is off, but I'm unsure what.

**Comment by JeffAtValve** [comment]
My guess is you have an off by one error.  Keep in mind some of the arrays in PHP are 1 indexed and some are 0.

**Comment by exts** [comment]
@JeffAtValve I'm using the exact code from this repo in the above example and that's the output. So something is off with the main source as well then.

Let me repeat: I copied the code from [_this_](https://github.com/ValveSoftware/ArtifactDeckCode/blob/master/PHP/deck_decoder.php) repo and ran it https://3v4l.org/92LIO and it's not showing all the cards.

**Comment by JeffAtValve** [comment]
The code is correct and the deck is correct.  I think you are getting tripped up somewhere.  Are you getting confused by signature cards?  The code is correct and the results as expected

**Comment by exts** [comment]
Then maybe I'm confused on how the Decoder is supposed to work.

For that deck it results 5 heroes and 19 card ID's right, Counting the cards' count value they equal up to `34` and that's still no where the size of that card deck which is 40 cards. That plus + 9 items + 5 heroes makes up a total of 54 in a deck, but none of those results add up to 54 in any shape or fashion?

Can you explain to me how the decoder is supposed to work because now that you're saying the code _is_ correct and that examples results that spits out a 19 sized array of cards and 5 heroes is _correct_ then I have no idea how this is supposed to work because there's clearly cards in that deck that isn't being shown in those results.

**Comment by JeffAtValve** [comment]
Sum all the quantities which are not items (including signature cards) = 40.  Sum all the quantities of items = 9.  Count ALL rows in the bottom portion of the deck viewers (items and mana cost cards) and subtract 5 (number of signature cards) = 24 - 5 = 19.

**Comment by exts** [comment]
Yet that data doesn't represent what you're telling me.

```
Array ( 
    [heroes] => Array ( 
        [0] => Array ( [id] => 4005 [turn] => 1 ) 
        [1] => Array ( [id] => 4008 [turn] => 3 ) 
        [2] => Array ( [id] => 10043 [turn] => 2 ) 
        [3] => Array ( [id] => 10059 [turn] => 1 ) 
        [4] => Array ( [id] => 10062 [turn] => 1 ) 
    ) 
    [cards] => Array ( 
        [0] => Array ( [id] => 3000 [count] => 2 )  -> x2 item card
        [1] => Array ( [id] => 3001 [count] => 2 )  -> x2 item card
        [2] => Array ( [id] => 3002 [count] => 2 )  -> x2 item card
        [3] => Array ( [id] => 10090 [count] => 2 )  -> x2 normal card
        [4] => Array ( [id] => 10092 [count] => 2 )   -> x2 normal card
        [5] => Array ( [id] => 10128 [count] => 2 )  -> x2 normal card 
        [6] => Array ( [id] => 10129 [count] => 2 )  -> x2 normal card 
        [7] => Array ( [id] => 10161 [count] => 2 )  -> x2 normal card 
        [8] => Array ( [id] => 10165 [count] => 2 )  -> x2 normal card 
        [9] => Array ( [id] => 10205 [count] => 1 )   -> x1 Item card
        [10] => Array ( [id] => 10215 [count] => 1 )  -> x1 Item card 
        [11] => Array ( [id] => 10218 [count] => 1 )  -> x1 Item card 
        [12] => Array ( [id] => 10270 [count] => 2 )  -> x2 normal card 
        [13] => Array ( [id] => 10307 [count] => 2 )   -> x2 normal card
        [14] => Array ( [id] => 10352 [count] => 2 )  -> x2 normal card 
        [15] => Array ( [id] => 10355 [count] => 2 )  -> x2 normal card 
        [16] => Array ( [id] => 10402 [count] => 2 )  -> x2 normal card 
        [17] => Array ( [id] => 10410 [count] => 1 )   -> x1 normal card
        [18] => Array ( [id] => 10418 [count] => 2 )   -> x2 normal card
    ) 
    [name] => Blue/Black Control 
)
```

The sum of all quantities above is 34, **its missing cards** here and that doesn't include signature cards. Including signature cards it's 39. The cards list has a mixture of both cards and items. Note this is the official code that PHP spits out.

Am I missing something here? I know my math isn't that off.

**Comment by JeffAtValve** [comment]
Yes, see the math I gave in my last comment.  First off, your normal card/item cards differentiation is wrong. Items are mixed into the card array.  You must cross reference with the card set to identify items propery.  Secondly, there are 15 signature cards, not 5.  

Your PHP array is correct which means your parser is correct.  No you just need to cross reference with the card set json.  Doing this will allow you to find the 15 signature cards and correctly identify which cards are items and which are not.

**Comment by exts** [comment]
Went ahead and mapped card ID's to the results PHP spit out:

```
4004  - x1 Debbi the Cunning	- Hero
4008  - x1 J'Muy the Wise	    - Hero
10043 - x1 Ogre Magi		    - Hero
10058 - x1 Necrophos		    - Hero
10062 - x1 Skywrath Mage	    - Hero
======================================
      = x5


3000  - x2 Travelers Cloak 	    - Item
3001  - x2 Leather Armor 	    - item
3002  - x2 Short Sword		    - Item
10205 - x1 Stonehall Cloak	    - Item
10215 - x1 Broadsword		    - Item
10218 - x1 Keenfolk Musket	    - Item
===========
        x9

10090 - x2 Relentless Zombie	    - Normal(Creep)
10092 - x2 Oglodi Vandal		    - Normal(Creep)
10128 - x2 Untested Grunt		    - Normal(Creep)
10129 - x2 Assassin's Apprentice 	- Normal(Creep)
10161 - x2 Trebuchets			    - Normal(Improvement)
10165 - x2 Iron Fog Goldmine		- Normal(Improvement)
10270 - x2 Grazing Shot			    - Normal(Spell)
10307 - x2 Foresight			    - Normal(Spell)
10352 - x2 Lightning Strike		    - Normal(Spell)
10355 - x2 Dimensional Portal		- Normal(Spell)
10402 - x2 Tower Barrage		    - Normal(Spell)
10410 - x1 Slay				        - Normal(Spell)
10418 - x2 Ventriloquy			    - Normal(Spell)
================================================
      - x25

Missing:
=======
x3 Battlefield Control
x3 Ignite
x3 No Accident
x3 Heartstopper Aura
x3 Mystic Flare
```

@JeffAtValve you notice something above? All the missing cards have a count of 3 O_o, and oddly enough the rest of those missing cards add up to the total 40 excluding items :) this is a bug man.

**Comment by JeffAtValve** [comment]
From a few posts ago

> . Are you getting confused by signature cards? The code is correct and the results as expected

This is clearly spelled out in the README as well.  Signature cards are NOT in the encoded decks.  This is by design and keeps deck codes small as the signature cards are redundant data.  Considering this issue closed. Glad you got to the bottom of your issue.

**Comment by exts** [comment]
@JeffAtValve ah, I'm an idiot. Signature cards = Hero cards.

**Comment by JeffAtValve** [comment]
:) All good.  Glad you got it figured out!
