### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by ottah** [ValveSoftware/ArtifactDeckCode#4]
- Having an attribute called `color : "Red" | "Green" | "Blue" | "Black"` makes more sense than `is_*` and having to check each color to see what it is.
- ingame_image has a background is it possible to get just the icon by itself? Like this [https://raw.githubusercontent.com/ottah/ArtifactDB/master/assets/icon/hero/jmuy_the_wise.png](url)
- Add a charges attribute for how many charges a card has.
- Active ability cooldown.
- Get Initiative should be an attribute
- Cross Lane should be an attribute

**Comment by elquintero** [comment]
I wanted to know how to get the cards in other languages eg; this does not work. 


https://playartifact.com/cardset/01/?language=ES-es or ?l=spanish

With http headers does not work either:

Content-Language: es-ES


only the labels come out in English:

"english":"Meepo"
},
.
.
.
"card_text":{
"english":"Move Meepo to an allied <span style='font-weight:bold;color:#ffffff;'>Meepo</span>'s lane.  Deal 2 damage to the new enemy neighbors."
},

I imagine that it is implemented for more languages, please keep us informed

Thank you.

**Comment by Uikae** [comment]
I agree on having cooldown separately if possible, this is what I do at the moment to get the cooldown if it can help someone:
```

if(ref['ref_type'] == 'active_ability') {
                                        //  get cooldown
                                        if(card['card_text']['english'] && card['card_text']['english'].indexOf('Active ')> -1){
                                            let cardText = card['card_text']['english'],
                                                replacedText = cardText.replace('Active ', '$'),
                                                textCooldown = replacedText.substring(replacedText.lastIndexOf('$') + 1, replacedText.lastIndexOf(":"));
                                            card['cooldown'] = parseInt(textCooldown,10);
                                        }
                                    }
```

**Comment by Spawnbroker** [comment]
I like the color approach from @ottah the best for future-proofing.

@elquintero They have said English is the only available language for now, I would imagine future updates will put more languages in the spots where you see English.

**Comment by JeffAtValve** [comment]
Crosslane and charges are down along with a couple other additions and fixes.  To address some questions, at this time color representation will not be changing.  If you need to reformat it you can always do so after downloading the blob.  We do this on the deck viewer internally.  As for hero icons with backgrounds, for now, we won't be able to provide those.  Feel free to make a separate issue for tracking.

As noted, other languages will be coming at a later date.

I'm going to close this out.  Can you folks make separate issues on the cooldown and initiative.

**Comment by elquintero** [comment]
I am seeing the changes in the https://playartifact.com/cardset/01 service at the language level. Thank you. I am developing an App for mobile. when will we have something definitive? Thank you very much again.
