### ISSUE TITLE
Disciple of Nevermore (10086)

### ISSUE THREAD

**Issue by Uikae** [ValveSoftware/ArtifactDeckCode#6]
The card should have -2 Armor not 254 XD

```
{
                "card_id": 10086,
                "base_card_id": 10086,
                "card_type": "Creep",
                "attack": 4,
                "armor": 254,
                "hit_points": 4,
                "references": []
}
```

**Comment by ottah** [comment]
Guessing they store armor as a unsigned int so it is looping back around.

**Comment by Uikae** [comment]
ye probable, no other cards have negative stats at the moment so that is the only exception I think.

**Comment by JeffAtValve** [comment]
Will fix before release.  Good catch!.
